version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: whack
    main: .
    binary: whack
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X github.com/ItsOrganic/whack/cmd.Version={{.Version}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - repository:
      owner: ItsOrganic
      name: homebrew-tap
    homepage: https://itsorganic.github.io/whack/
    description: A fast hot reloader for Go
    license: MIT
